create extension if not exists pgcrypto;

create table if not exists public.sync_changes (
  seq bigint generated by default as identity primary key,
  room_id text not null,
  note_id text not null,
  change_id text not null unique,
  device_id text not null,
  ts bigint not null,
  kind text not null,
  payload jsonb not null,
  token_hash text,
  signer_device_id text,
  signer_public_key text,
  signature text,
  created_at timestamptz not null default now()
);

alter table public.sync_changes add column if not exists token_hash text;
alter table public.sync_changes add column if not exists signer_device_id text;
alter table public.sync_changes add column if not exists signer_public_key text;
alter table public.sync_changes add column if not exists signature text;

create index if not exists sync_changes_room_seq_idx on public.sync_changes (room_id, seq);
create index if not exists sync_changes_room_change_idx on public.sync_changes (room_id, change_id);
create index if not exists sync_changes_token_hash_idx on public.sync_changes (token_hash);

alter table public.sync_changes enable row level security;
alter table public.sync_changes force row level security;

create or replace function public.leiser_request_token()
returns text
language sql
stable
as $$
  select coalesce(
    nullif(current_setting('request.headers', true)::jsonb ->> 'x-leiser-token', ''),
    nullif(current_setting('request.header.x-leiser-token', true), '')
  )
$$;

create or replace function public.leiser_token_ok(expected_hash text)
returns boolean
language sql
stable
as $$
  select expected_hash is not null
    and public.leiser_request_token() is not null
    and encode(digest(public.leiser_request_token(), 'sha256'), 'hex') = expected_hash
$$;

drop policy if exists sync_changes_select_token on public.sync_changes;
drop policy if exists sync_changes_insert_token on public.sync_changes;
drop policy if exists sync_changes_update_token on public.sync_changes;

create policy sync_changes_select_token
on public.sync_changes
for select
to anon
using (public.leiser_token_ok(token_hash));

create policy sync_changes_insert_token
on public.sync_changes
for insert
to anon
with check (public.leiser_token_ok(token_hash));

create policy sync_changes_update_token
on public.sync_changes
for update
to anon
using (public.leiser_token_ok(token_hash))
with check (public.leiser_token_ok(token_hash));
